"""Codemap generator -- proje haritasi cikarir."""

import ast
import sys
from pathlib import Path
from rich.console import Console

console = Console()

SKIP_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", ".next",
    "dist", "build", ".tox", ".pytest_cache", ".mypy_cache", "egg-info",
}
ENTRY_POINT_NAMES = {
    "main.py", "app.py", "cli.py", "__main__.py", "index.ts",
    "index.js", "server.py", "server.ts", "manage.py",
}
MAX_FILES = 500


def generate_codemap(project_path: Path) -> str:
    """Proje codemap'i uret (markdown formatinda)."""
    project_path = Path(project_path)
    modules = _discover_modules(project_path)
    entries = find_entry_points(project_path)
    dep_graph = _build_dependency_graph(project_path, modules)

    lines = [f"# {project_path.name} -- Codemap\n"]
    lines.append("Generated by claude-forge\n")

    lines.append("## Modules\n")
    for mod_path, files in sorted(modules.items()):
        rel = mod_path.relative_to(project_path) if mod_path != project_path else Path(".")
        lines.append(f"- `{rel}/` -- {len(files)} files")

    if entries:
        lines.append("\n## Entry Points\n")
        for ep in entries:
            lines.append(f"- `{ep}`")

    if dep_graph:
        lines.append("\n## Dependency Graph\n")
        lines.append("```")
        for src, targets in sorted(dep_graph.items()):
            for t in sorted(targets):
                lines.append(f"{src} -> {t}")
        lines.append("```")

    return "\n".join(lines) + "\n"


def _discover_modules(project_path: Path) -> dict[Path, list[str]]:
    modules: dict[Path, list[str]] = {}
    count = 0
    for item in sorted(project_path.rglob("*")):
        if count >= MAX_FILES:
            break
        if any(sd in item.parts for sd in SKIP_DIRS):
            continue
        if item.is_file() and item.suffix in {".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs"}:
            count += 1
            parent = item.parent
            if parent not in modules:
                modules[parent] = []
            modules[parent].append(item.name)
    return modules


def find_entry_points(project_path: Path) -> list[str]:
    entries = []
    for item in project_path.iterdir():
        if item.is_file() and item.name in ENTRY_POINT_NAMES:
            entries.append(item.name)

    pkg_json = project_path / "package.json"
    if pkg_json.exists():
        try:
            import json
            data = json.loads(pkg_json.read_text(encoding="utf-8"))
            main = data.get("main")
            if main:
                entries.append(f"package.json -> {main}")
        except Exception:
            pass
    return sorted(set(entries))


def analyze_python_imports(file_path: Path) -> list[str]:
    """Python dosyasindaki local import'lari analiz et (ast ile)."""
    try:
        source = file_path.read_text(encoding="utf-8", errors="ignore")
        tree = ast.parse(source)
    except (SyntaxError, ValueError):
        return []

    imports = []
    stdlib_modules = set(sys.stdlib_module_names) if hasattr(sys, "stdlib_module_names") else set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = alias.name.split(".")[0]
                if top not in stdlib_modules:
                    imports.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.level == 0:
                top = node.module.split(".")[0]
                if top not in stdlib_modules:
                    imports.append(node.module)
            elif node.module and node.level > 0:
                imports.append(node.module)
    return imports


def _build_dependency_graph(
    project_path: Path, modules: dict[Path, list[str]]
) -> dict[str, set[str]]:
    graph: dict[str, set[str]] = {}
    for mod_path, files in modules.items():
        for fname in files:
            if not fname.endswith(".py"):
                continue
            fpath = mod_path / fname
            imports = analyze_python_imports(fpath)
            rel_mod = str(mod_path.relative_to(project_path)).replace("\\", "/").replace("/", ".")
            if rel_mod == ".":
                rel_mod = "root"

            for imp in imports:
                top = imp.split(".")[0]
                for other_mod_path in modules:
                    other_rel = str(other_mod_path.relative_to(project_path)).replace("\\", "/")
                    if top in other_rel or other_rel.startswith(top):
                        target = other_rel.replace("/", ".") or "root"
                        if target != rel_mod:
                            if rel_mod not in graph:
                                graph[rel_mod] = set()
                            graph[rel_mod].add(target)
    return graph


def write_codemap(project_path: Path, output_path: Path | None = None) -> Path:
    """Codemap uret ve dosyaya yaz."""
    project_path = Path(project_path)
    content = generate_codemap(project_path)
    if output_path is None:
        output_path = project_path / "docs" / "CODEMAP.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    console.print(f"[green][OK][/green] Codemap: {output_path}")
    return output_path
